### ISSUE TITLE
how to run tests?

### ISSUE THREAD

**Issue by fuse-mars** [Neil-G/redux-mastermind#5]
when i run `npm test`, the test runner stays running forever

**Comment by fuse-mars** [comment]
@Neil-G  the branch `bugfix/test-runner` fixes this issue temporary.

Issue is due to the fact that you are opening a [firebase database connection](https://github.com/Neil-G/redux-mastermind/blob/master/src/configureFirebase.js#L11)

And this prevents the test runner from exiting

**Comment by Neil-G** [comment]
The tests run properly, but hang at the end because I'm returning promises that do not resolve.  I think I should implement this package to deal with tests properly using tape test suite

https://github.com/jprichardson/tape-promise

**Comment by Neil-G** [comment]
fixed by Mars- thanks!
