### ISSUE TITLE
using Object.assign (vs Immutable)

### ISSUE THREAD

**Issue by Neil-G** [Neil-G/redux-mastermind#7]
Hey guys, I think I can change mastermind to not use Immutable, but I wanted to get feedback on the idea.

This is what the new code would look like:
```javascript
const exampleAction = {
  branch: 'todos'
  reducerFunction: ({ state, res, error, store }) => {
     // you have access to api response, error, the state of the current branch, and the store
     // then you transform the state (which is sugar for store.getState()[action.branch])
     return newState
  }
}
```

which ultimately gets transformed to this (by the processActionGroup processorPart):

```javascript
const processedExampleAction = {
  type: exampleAction.branch // 'todos'
  newState: action.reducerFunction({ state, res, error, store }) // the return value of this function call
}

```

The reducer function will then look something like:

```javascript
const reducerFunction = (state, action) => {
  switch(action.type) {
    case 'todos': 
       return Object.assign({}, state, action.newState)
    default
       return state  
  }
}
```

Simpler API, no dependence on Immutable.  Thoughts?

**Comment by fuse-mars** [comment]
Seems ok but one concern is the **naming** 

Using a *branch*, will resonates well with people if there is involvement of *ImmutableJs*, because all operations that a person perform (ex: `setIn`, `updateIn`, ...), are done on a given *branch* (ex: ['todos', '1', 'completed'])

**Comment by Neil-G** [comment]
I'm not making this addition, but will instead make mastermind able to take a store argument and alter reducers if they do not use immutable.
